Add mock to test requirements.
Fixes error `AttributeError: 'module' object has no attribute 'test_configargparse'`
Credits to @hlieberman for finding the cause.
Fixes #125.